name: Build EXE

on:
  push:
    branches:
      - main  # or whatever branch you want to trigger on
  workflow_dispatch:   # 👈 allows manual run

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: List current directory
      run: |
        pwd
        ls -la
        
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Run PyInstaller with repo Python
      run: |
        ./python313/python.exe -m PyInstaller --onefile your_script.py

    - name: Upload EXE as artifact
      uses: actions/upload-artifact@v4
      with:
        name: my-exe
        path: dist/*.exe
