name: Build EXE

on:
  push:
    branches:
      - main  # or whatever branch you want to trigger on
  workflow_dispatch:   # 👈 allows manual run

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
        
    - name: Run PyInstaller with repo Python
      run: |
        ./ExcelInsuranceProviderHelper/Python313/python.exe -m PyInstaller --onefile --noconsole --name Excel_Insurance_Provider_Helper ./ExcelInsuranceProviderHelper/MainApp.py

    - name: Upload EXE as artifact
      uses: actions/upload-artifact@v4
      with:
        name: my-exe
        path: dist/*.exe
